package eu.jhouse.android.mqtt;

/**
 * @author tomekk
 * @since 22.02.11, 19:54
 */
public enum MQTTConnectionStatus {
	INITIAL,
	CONNECTING,
	CONNECTED,
	NOTCONNECTED_WAITINGFORINTERNET,
	NOTCONNECTED_USERDISCONNECT,
	NOTCONNECTED_DATADISABLED,
	NOTCONNECTED_UNKNOWNREASON;
}
